# .github/workflows/ci.yml
name: .NET CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore ApiProcessing.sln

      - name: Build
        run: dotnet build ApiProcessing.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ApiProcessing.sln --configuration Release --no-build
